### ISSUE TITLE
cant load into fedora using rEFInd

### ISSUE THREAD

**Issue by cryptothenitwit** [jlobue10/SteamDeck_rEFInd#111] opened 2024-03-10 19:34 UTC
I have followed a tutorial to install and use rEFInd to dual boot my Steam deck, and from the menu, I can select Steam os and it will load just fine but it gives me this error when I try to load into fedora Linux. I know I have installed Fedora correctly because if I hold down vol- and power and select Fedora to boot into, it loads just fine. can anyone tell me how to fix this, what I did wrong or what is happening?
![IMG_20240310_152805801_HDR](https://github.com/jlobue10/SteamDeck_rEFInd/assets/139021835/02079d73-eda6-47c0-9da6-ac989bde648a)

**Comment by F5T3** [comment] 2024-06-17 20:56
> What does your installed `refind.conf` file look like?

It's an error with his grub not with any of his rEFInd. He either installed grub wrong or made his partition read-only.

**Comment by jlobue10** [comment] 2024-06-17 21:02
> > What does your installed `refind.conf` file look like?
> 
> It's an error with his grub not with his rEFInd. He either installed grub wrong or made his partition read-only.

Fair enough. I admittedly didn't look too closely and have grown a bit tired of people expecting me to be generic troubleshooting because they followed a guide somewhere and made a mistake along the way.

**Comment by F5T3** [comment] 2024-06-28 19:27
> I don't necessarily think this person's GRUB is the problem if he (or she) is able to boot into Fedora from the BIOS options.

In the error message it states that GEUB can't load a partition correctly, the person has to uninstall grub from his System, with a live USB. But he (or she) could also try to fix the mounting of his partitions, which also probably is in a live USB of Fedora.

**Comment by jlobue10** [comment] 2024-06-28 19:39
The problem is I'm not given enough information, and the information that I'm requesting to help my understanding of the larger issue is not given. I don't have the time to help others if I can't be given basic information to assist with my overall understanding of their bigger issue, especially if and when it's not necessarily a problem with my software and this repo here.

For what it's worth, I have SteamOS, Nobara (Fedora based) and W11 triple boot working on my OLED and LCD Steam Decks, so I know how certain config files and EFI boot entries should look like.

Without that basic information that I'm requesting (active `refind.conf` file and `efibootmgr` output), it's not worth my time to even start looking into this, and it's especially not worth my time arguing something that is not the point based on potentially incorrect assumptions made by a 3rd party person. Closing this issue. Reopen the issue with `refind.conf` file and `egibootmgr` output if you still need support, as these will be the basis for potential follow on questions.

**Closed by jlobue10** 2024-06-28 19:39 UTC
