### ISSUE TITLE
Unable to Disabling Windows EFI

### ISSUE THREAD

**Issue by tehblastar** [jlobue10/SteamDeck_rEFInd#18] opened 2022-12-24 04:16 UTC
Sorry if this is the incorrect place, but I am having an error disabling the windows efi entry to have the deck boot into rEFInd. 

I had the common error of SteamOS deleting its own EFI entry, and following the readme I managed to re-enable it and reinstall rEFInd. SteamOS and rEFInd both work if manually selected in the boot loader, but the deck boots into windows by default.  I believe the rEFInd script also is unable to disable the windows EFI. The Windows EFI file exists, and if I boot into rEFInd using the boot loader, I can launch windows from rEFInd. I tried disabling the windows entry in manually with the error below.

```
(1)(deck@steamdeck ~)$ sudo efibootmgr

[sudo] password for deck:

BootCurrent: 0001

Timeout: 0 seconds

BootOrder: 0002,0000,0001,2001,2002,2003

Boot0000* rEFInd HD(1,GPT,676c28fe-3c8e-e04f-8a04-bfc22731e99d,0x800,0x20000)/File(\efi\refind\refind_x64.efi)

Boot0001* SteamOS HD(1,GPT,676c28fe-3c8e-e04f-8a04-bfc22731e99d,0x800,0x20000)/File(\efi\steamos\steamcl.efi)

Boot0002* Windows Boot Manager HD(1,GPT,676c28fe-3c8e-e04f-8a04-bfc22731e99d,0x800,0x20000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000000000100000010000000040000007fff0400

Boot2001* EFI USB Device RC

Boot2002* EFI DVD/CDROM RC

Boot2003* EFI Network RC

(deck@steamdeck ~)$ efibootmgr -b 0002 -A

efibootmgr: Boot entry 2 not found

Could not set active state for Boot0002: No such file or directory

```

Some things I have tried:
- Changing the boot order. Just changes itself back when restarting
- Reinstalling rEFInd

Any ideas how to disable the windows efi?

**Comment by jlobue10** [comment] 2022-12-24 05:17
There is one more thing that you should have tried, reading the README.

Closing this as it's basically a duplicate of solved [issue 12](https://github.com/jlobue10/SteamDeck_rEFInd/issues/12).

Disabling the Windows EFI entry now requires being done from the command line when booted from the SteamOS recovery image, or being done from Windows using something like EasyUEFI trial or a proper `bcdedit` command. This is addressed in the updated README file.

**Closed by jlobue10** 2022-12-24 05:17 UTC
