### ISSUE TITLE
Installs but then only boots to Windows automatically 

### ISSUE THREAD

**Issue by krittinen** [jlobue10/SteamDeck_rEFInd#82] opened 2023-10-03 04:18 UTC
I'm running SteamOS 3.5 Preview and Windows 11 both on the NVMe drive, when I try to install refind using the .desktop file from the tarball it "succeeds" but after rebooting it reboots back to Windows automatically.

I tried to do the compilation as per the guide but it failed on my Deck.

**Comment by jlobue10** [comment] 2023-10-03 06:59
Yes it appears that the installer script that the GUI kicks off may not be working right now for some reason (worked fine for months...). I need to debug why.

In the meantime, please use the [SteamDeck_rEFInd_install.sh](https://github.com/jlobue10/SteamDeck_rEFInd/blob/main/SteamDeck_rEFInd_install.sh) script from the cloned repository for the "Install rEFInd" step.

**Comment by acoolrocket** [comment] 2023-10-07 19:09
> Yes it appears that the installer script that the GUI kicks off for the "Install rEFInd" step may not be working right now for some reason (worked fine for months...). I need to debug why.
> 
> In the meantime, please use the [SteamDeck_rEFInd_install.sh](https://github.com/jlobue10/SteamDeck_rEFInd/blob/main/SteamDeck_rEFInd_install.sh) script from the cloned repository for the "Install rEFInd" step.

I'm super novice to Linux, so wondering the exact steps to initiate this .sh script.

**Comment by jlobue10** [comment] 2023-10-07 19:18
```
git clone https://github.com/jlobue10/SteamDeck_rEFInd/
cd SteamDeck_rEFInd
chmod +x install-GUI.sh
./install-GUI.sh
```

**Comment by acoolrocket** [comment] 2023-10-07 19:20
> ```
> git clone https://github.com/jlobue10/SteamDeck_rEFInd/
> cd SteamDeck_rEFInd
> chmod +x install-GUI.sh
> ./install-GUI.sh
> ```

What if I already got the GUI installed? I'm pretty much at this step in this tutorial btw: https://youtu.be/ubWPIf2DbvE?list=PL76L9goV4SndYDRNsmo_7xuEQnQ9U1TMG&t=487

**Comment by jlobue10** [comment] 2023-10-07 19:22
Edited for proper command... I'm basically in single dad mode (with very few free moments), and I copied that snippet to edit from phone. Sorry for confusion.

**Comment by acoolrocket** [comment] 2023-10-07 19:23
> Edited for proper command... I'm basically in single dad mode (with very few free moments), and I copied that snippet to edit from phone. Sorry for confusion.

No prob, so you can do the git clone thing twice even if I already did the installation just to run this script?

**Comment by jlobue10** [comment] 2023-10-07 19:25
If you've already cloned, then you can skip that step.

**Comment by Hertzccc** [comment] 2023-10-07 19:32
I got this error when running this file: SteamDeck_rEFInd_install.sh
error: refind: signature from "David Runge <dvzrv@archlinux.org>" is unknown trust

Can you please tell me how to do next?

**Comment by acoolrocket** [comment] 2023-10-07 19:33
Script installed correctly but in the Boot Manager I'm still missing the rEFInd boot device that should be appearing like here: https://youtu.be/ubWPIf2DbvE?list=PL76L9goV4SndYDRNsmo_7xuEQnQ9U1TMG&t=596

**Comment by jlobue10** [comment] 2023-10-07 19:39
> I got this error when running this file: SteamDeck_rEFInd_install.sh error: refind: signature from "David Runge [dvzrv@archlinux.org](mailto:dvzrv@archlinux.org)" is unknown trust
> 
> Can you please tell me how to do next?

Please show me full terminal output. Also, is your SteamOS fully up to date? What branch are you on (stable, beta, etc.)?

**Comment by jlobue10** [comment] 2023-10-07 19:39
> Script installed correctly but in the Boot Manager I'm still missing the rEFInd boot device that should be appearing like here: https://youtu.be/ubWPIf2DbvE?list=PL76L9goV4SndYDRNsmo_7xuEQnQ9U1TMG&t=596

Redo the create config and install config steps from the GUI. Latest SteamOS updates seems to have broken a lot...

**Comment by acoolrocket** [comment] 2023-10-07 19:41
> > Script installed correctly but in the Boot Manager I'm still missing the rEFInd boot device that should be appearing like here: https://youtu.be/ubWPIf2DbvE?list=PL76L9goV4SndYDRNsmo_7xuEQnQ9U1TMG&t=596
> 
> Redo the create config and install config steps from the GUI. Latest SteamOS updates seems to have broken a lot...

Yeah saw 3.5 causing this, btw for the config thing, should I first execute the script in Konsole then open the GUI to create/install config?

**Comment by Hertzccc** [comment] 2023-10-07 19:41
> > I got this error when running this file: SteamDeck_rEFInd_install.sh error: refind: signature from "David Runge [dvzrv@archlinux.org](mailto:dvzrv@archlinux.org)" is unknown trust
> > Can you please tell me how to do next?
> 
> Please show me full terminal output. Also, is your SteamOS fully up to date? What branch are you on (stable, beta, etc.)?

I updated the steamos just now, and in stable mode. This is the whole output:


➜ SteamDeck_rEFInd (main) ✗ ./SteamDeck_rEFInd_install.sh            
deck P 2023-10-03 0 99999 7 -1
Password is already set.
==> Appending keys from archlinux.gpg...
==> Updating trust database...
gpg: next trustdb check due at 2023-10-27
:: Synchronizing package databases...
 jupiter-rel is up to date
 holo-rel is up to date
 core-rel is up to date
 extra-rel is up to date
 community-rel is up to date
 multilib-rel is up to date
resolving dependencies...
looking for conflicting packages...

Packages (1) refind-0.13.3.1-1

Total Download Size:   0.95 MiB
Total Installed Size:  1.88 MiB

:: Proceed with installation? [Y/n] 
:: Retrieving packages...
 refind-0.13.3.1-1-any                                 968.7 KiB  1023 KiB/s 00:01 [###############################################] 100%
(1/1) checking keys in keyring                                                     [###############################################] 100%
(1/1) checking package integrity                                                   [###############################################] 100%
error: refind: signature from "David Runge <dvzrv@archlinux.org>" is unknown trust
:: File /var/cache/pacman/pkg/refind-0.13.3.1-1-any.pkg.tar.zst is corrupted (invalid or corrupted package (PGP signature)).
Do you want to delete it? [Y/n] 
error: failed to commit transaction (invalid or corrupted package (PGP signature))
Errors occurred, no packages were upgraded.
sudo: refind-install: command not found
BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0001,0002,0000,2001,2002,2003
Boot0000* SteamOS       HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\steamos\steamcl.efi)
Boot0001* rEFInd        HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\refind\refind_x64.efi)
Boot0002* Windows Boot Manager  HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000030000100000010000000040000007fff0400
Boot2001* EFI USB Device        RC
Boot2002* EFI DVD/CDROM RC
Boot2003* EFI Network   RC
efibootmgr: Boot entry 2 not found
Could not set active state for Boot0002: No such file or directory
Invalid bootnum value: FFFFFFFFFFFFFFF5

BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0002,0000,2001,2002,2003
Boot0000* SteamOS       HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\steamos\steamcl.efi)
Boot0002* Windows Boot Manager  HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000030000100000010000000040000007fff0400
Boot2001* EFI USB Device        RC
Boot2002* EFI DVD/CDROM RC
Boot2003* EFI Network   RC
BootNext: 0001
BootCurrent: 0000
Timeout: 0 seconds
BootOrder: 0001,0002,0000,2001,2002,2003
Boot0000* SteamOS       HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\steamos\steamcl.efi)
Boot0002* Windows Boot Manager  HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\Microsoft\Boot\bootmgfw.efi)57494e444f5753000100000088000000780000004200430044004f0042004a004500430054003d007b00390064006500610038003600320063002d0035006300640064002d0034006500370030002d0061006300630031002d006600330032006200330034003400640034003700390035007d00000030000100000010000000040000007fff0400
Boot2001* EFI USB Device        RC
Boot2002* EFI DVD/CDROM RC
Boot2003* EFI Network   RC
Boot0001* rEFInd        HD(1,GPT,456e6fa0-f72f-c24c-8cdf-81099a933d88,0x800,0x20000)/File(\EFI\refind\refind_x64.efi)

rEFInd has now been installed (assuming pacman is functional).

**Comment by jlobue10** [comment] 2023-10-07 19:58
Can you try

`sudo rm /var/cache/pacman/pkg/refind-0.13.3.1-1-any.pkg.tar.zst`

and then try the script again?

**Comment by Hertzccc** [comment] 2023-10-07 20:02
> Can you try
> 
> `sudo rm /var/cache/pacman/pkg/refind-0.13.3.1-1-any.pkg.tar.zst`
> 
> and then try the script again?

I checked the /var/cache/pacman/pkg/ and find it is not here. May be that's the point

**Comment by jlobue10** [comment] 2023-10-07 20:04
Yeah not sure. I haven't touched my Steam Deck in months. I'd suggest running the non-Pacman (Sourceforge) installer instead.

**Comment by Hertzccc** [comment] 2023-10-07 20:05
Thank you. I would try to run the non-Pacman installer.

**Comment by jlobue10** [comment] 2023-10-07 20:07
Give me a few minutes to update that script. Doing my best from my phone. :)

**Comment by jlobue10** [comment] 2023-10-07 20:11
0.14.0.2 seems to be the latest. Please try the non-Pacman installer and let me know how it goes. If you're using the GUI, you'd want to do the create config and install config steps afterwards. Thanks.

**Comment by Hertzccc** [comment] 2023-10-07 20:12
Thank you again! This works very well. You are awesome!

**Comment by jlobue10** [comment] 2023-10-07 20:15
> Thank you again! This works very well. You are awesome!

So all working now? Sweet! Seems I have some stuff to debug though when baby is sleeping...

**Comment by Hertzccc** [comment] 2023-10-07 20:20
Wish you and your baby a good night.(Although it's 4:20am here

**Comment by krittinen** [comment] 2023-10-07 23:49
I can also confirm that the no-pacman install also works.

**Comment by jlobue10** [comment] 2023-10-09 18:37
Thanks for confirmation. The Sourceforge installation method option from the GUI also has been confirmed to be working, so we can chalk this up to a `pacman` issue, most likely.

**Comment by jlobue10** [comment] 2023-11-19 21:31
Closing this issue

**Closed by jlobue10** 2023-11-19 21:31 UTC
