### ISSUE TITLE
Error. Need help pls

### ISSUE THREAD

**Issue by Mmerc93** [jlobue10/SteamDeck_rEFInd#41] opened 2023-02-20 06:03 UTC
Hello. I tried following the install on a YouTube tutorial and I accidentally hit enter when copying and pasting from this thread on the steam deck. And idk if that is the reason or not. But I am getting this error code. Also like in the video. The password pop up didn’t open for me. Do you know how I can uninstall then start completely over. Or anything I can do to fix this error. I’m just trying to dual boot steam and windows. 
![F3635590-DB60-400A-819E-5724ECAFB3FA](https://user-images.githubusercontent.com/125854479/220022681-6ca05f66-173e-48bf-b347-fbbfde6ca5f9.jpeg)
![54CEE51A-6406-4513-B493-5672B92F394D](https://user-images.githubusercontent.com/125854479/220022697-27ea1d36-e12f-4440-9327-ce0a998a13fb.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 11:09
The password pop-up no longer appears. This was a change to be more friendly for installing the GUI over an SSH connection.

Instead, you are now greeted with a reminder to have the password set before continuing at the beginning. Press enter to continue from that. When the installation script prompts for the `sudo` password, enter it in the terminal. It seems that your installation errored out because it did not have `sudo` permissions. Please try again and ensure that you are entering your `sudo` password properly.

**Comment by Mmerc93** [comment] 2023-02-20 12:20
Sudo password is the same as the user password I set up, correct? Also, how do I enter it? I can't type anything after I click continue after it gives me the alert that says to make sure I have my password set.

**Comment by jlobue10** [comment] 2023-02-20 12:23
Yes, same as user. You are entering it. The default settings give no visual feedback though in the terminal of this typing. If you enter it wrongly, you will be prompted to re-enter it.

**Comment by Mmerc93** [comment] 2023-02-20 15:08
So I typed everything in and re tried it this morning. First pic is of what I typed in following with a password. Second pic is "gui compile failed" notice. I followed everything on the video and changed my password using the passwd command. Is there any alternative to dual booting? Also it says to try again after ensuring that your cloned repo is up to date? And Pac-Man config is normal.

**Comment by Mmerc93** [comment] 2023-02-20 15:08
![image](https://user-images.githubusercontent.com/125854479/220142364-e0f09152-008e-43d0-b738-a178748e6f85.jpeg)

![image](https://user-images.githubusercontent.com/125854479/220142407-5610ce9d-7152-4fc0-b6bf-9c19d2fbe23c.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 15:25
Are the 26 `base-devel` packages even installing? Is there any output that you're not showing me between the first screenshot and second screenshot (scrolling up in command line)?

**Comment by jlobue10** [comment] 2023-02-20 15:28
What does your `/etc/pacman.conf` file (view it with `sudo nano /etc/pacman.conf` look like for these lines?

```
[jupiter-beta]
[holo-beta]
[core-beta]
[extra-beta]
[community-beta]
[multilib-beta]
```
I'm hoping they say `*-rel` and not `*-beta` or something different than rel (for release).

**Comment by jlobue10** [comment] 2023-02-20 15:45
Did you perform a SteamOS reimage from the recovery USB before attempting all of this (different from factory reset in settings)?
Is your SteamOS installation up to date with all of the latest updates? Is your SteamOS on the `Stable` branch?

**Comment by Mmerc93** [comment] 2023-02-20 15:47
https://user-images.githubusercontent.com/125854479/220150474-0b7a717c-b2b4-459c-9329-8a52110ad7a9.MOV

**Comment by Mmerc93** [comment] 2023-02-20 15:50
Hopefully you're able to see the video clearly. Looks like everything was good until the end

**Comment by jlobue10** [comment] 2023-02-20 15:50
Looks like packages are installing properly. If you type `which g++` from the command line, what is the result?

**Comment by Mmerc93** [comment] 2023-02-20 15:53
![image](https://user-images.githubusercontent.com/125854479/220151903-5d45d14c-0dd6-4847-9b6f-cbc6cdc4aea4.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 16:00
What about `which qmake` and `which make` ?

**Comment by Mmerc93** [comment] 2023-02-20 16:04
> Did you perform a SteamOS reimage from the recovery USB before attempting all of this (different from factory reset in settings)?
> 
> Is your SteamOS installation up to date with all of the latest updates? Is your SteamOS on the `Stable` branch?

Yes I did the reimage after doing the ssd upgrade. It is also on stable.

**Comment by jlobue10** [comment] 2023-02-20 16:05
We can try to manually compile it from the command line. Try these, one after the other.

```
cd $HOME/.SteamDeck_rEFInd/GUI/src
qmake
make clean
make
```

What is the result?

**Comment by Mmerc93** [comment] 2023-02-20 16:28
![image](https://user-images.githubusercontent.com/125854479/220159043-35c14008-3a64-42d1-bfcd-1ce4b0ad8691.jpeg)

did I type it right?

**Comment by jlobue10** [comment] 2023-02-20 16:35
Yes. It appears to be having a problem on the `qmake` step for some reason. I have not seen this before. Something seems really messed up here...

**Comment by jlobue10** [comment] 2023-02-20 16:36
What is the output for `qmake --version`?

**Comment by Mmerc93** [comment] 2023-02-20 16:43
![image](https://user-images.githubusercontent.com/125854479/220162054-649ac65e-d187-49d3-8a9a-55c64482ecfd.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 16:50
Maybe it's just easiest to completely remove the cloned folder and the `~/.SteamDeck_rEFInd` (separate hidden directory) folder and try again. Before doing that, please ensure that you have all of the latest updates installed for SteamOS on your system, and please restart your Steam Deck.

**Comment by Mmerc93** [comment] 2023-02-20 16:54
> Maybe it's just easiest to completely remove the cloned folder and the `~/.SteamDeck_rEFInd` (separate hidden directory) folder and try again. Before doing that, please ensure that you have all of the latest updates installed for SteamOS on your system, and please restart your Steam Deck.

Any way you could help explain how to find and delete both folders? And all updated from steamOS are up to date

**Comment by jlobue10** [comment] 2023-02-20 16:56
Just open Dolphin and go to your `/home/deck` folder. You should see both your cloned folder and the hidden folder. You may have to enable the option to make hidden folders viewable. Deleting both folders from the GUI is probably easiest and is hopefully self-explanatory.

**Comment by Mmerc93** [comment] 2023-02-20 17:05
Ok. So delete both of the .SteamDeck_rEFInd folders? ![image](https://user-images.githubusercontent.com/125854479/220166153-9416f80a-220a-4549-98fa-69d147460c0b.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 17:12
Yes, delete both the `/home/deck/SteamDeck_rEFInd` and `/home/deck/.SteamDeck_rEFInd` folders, and then try again from the beginning of the GUI installation method steps. Do not modify any of the cloned files in an intermediate step.

**Comment by jlobue10** [comment] 2023-02-20 18:16
Yes, I can upload the precompiled binary with a md5 checksum. Give me a little bit. I'm busy with baby right now.

**Comment by Mmerc93** [comment] 2023-02-20 18:20
Ok thanks. I am not smart with computers related anything at all so you're helping me out quite a bit. Just let me know

**Comment by jlobue10** [comment] 2023-02-20 18:45
I just made a new release [here](https://github.com/jlobue10/SteamDeck_rEFInd/releases/tag/v1.1.5.1). Although I am unable to replicate your issue, you should be able to use the provided `rEFInd_GUI` executable. Please read the release instructions. Let me know if you have any questions or issues with that.

**Comment by Mmerc93** [comment] 2023-02-20 19:35
So I downloaded the file on the deck. But I'm trying to find a way to drag that file from downloads into the gui portion of the .SteamDeck_rEFInd folder. I barely can control this device as it it lol.

**Comment by Mmerc93** [comment] 2023-02-20 19:39
Ok. So I believe I got it. Now do I pick back up on this part of the YouTube video? Or do I need to do anything with the commands in konsole? ![image](https://user-images.githubusercontent.com/125854479/220187002-7d193438-96cd-4e81-8585-97d660ceff93.jpeg)

**Comment by jlobue10** [comment] 2023-02-20 19:43
Click the Install rEFInd button, and then from there follow the video. The rest is covered in the GUI README, and is also (hopefully) pretty intuitive. Basically setup the GUI for your configuration (may be good by default), then click 'Create Config' followed by 'Install Config'.

**Comment by Mmerc93** [comment] 2023-02-20 20:57
I think I got it. Set up partition and downloaded windows. I believe I have to wait till I get home to install drivers next because I can't use keyboard in windows. But after that I hope it will work. Thanks again for all the help. I will let you know later tonight if it worked.

**Comment by jlobue10** [comment] 2023-02-20 21:16
Yep, no worries. I think I may just provide a pre-compiled GUI bundled with future releases, unless we can figure out and fix what the issue is here. Let me know how it goes.

**Comment by Mmerc93** [comment] 2023-02-20 22:20
By chance. Would you know anything about the steam deck audio drivers for windows 11. I don't see an option when I right click to "install" 2 of the audio drivers on the steam deck. I know it's a problem but people have said they have fixed it but I can't seem to find my exact problem

**Comment by Mmerc93** [comment] 2023-02-20 22:21
Nevermind. I figured it out

**Comment by Mmerc93** [comment] 2023-02-24 16:32
Got everything working. Thank you very much. That pre compiled file was key for me.

**Comment by jlobue10** [comment] 2023-02-24 16:39
Thank you for confirming. I'll close the issue now and just provide a pre-compiled GUI with any future releases. I think the only updates that I'm looking into now are allowing typing in the PNG line edit boxes (needs a validator for existing PNG file or reject the input) and possibly two buttons, one to enable the `systemd` service and one to disable it. Other than that, I am happy with the GUI.

**Closed by jlobue10** 2023-02-24 16:39 UTC
